Home page and logged out page styling
the-collab-lab/tcl-67-smart-shopping-list pull request #122
Opened 2024-04-04 19:42 UTC by jtkabenni

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

Updates to home page and logged out page styling according to high fidelity mockups. Also changed name to clevercart and implemented colors. 

## Related Issue

#121 
#107 
#105 

## Acceptance Criteria

## Type of Changes

Styling update

## Updates

### Before

Mobile:
<img width="500" alt="Screenshot 2024-04-04 at 1 40 23 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/c31b8418-ece2-489e-87a9-e3c78667ca09">
<img width="500" alt="Screenshot 2024-04-04 at 1 40 18 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/ed93b1f8-9a19-4a1e-af28-cb4a505243c6">

web:
<img width="1440" alt="Screenshot 2024-04-04 at 1 40 11 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/4e95d385-9cdd-4397-9a7e-80c2893099f5">
<img width="1440" alt="Screenshot 2024-04-04 at 1 40 03 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/5c590a3f-9ba7-493c-a23a-86e8e5d78f4d">

### After
Mobile: 
<img width="499" alt="Screenshot 2024-04-04 at 1 38 27 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/b4f70662-9b46-4e41-85fe-570500c64ee3">
<img width="499" alt="Screenshot 2024-04-04 at 1 38 15 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/a9b77000-240f-4109-ae9a-7e5fc04dc33d">

Web: 
<img width="1440" alt="Screenshot 2024-04-04 at 1 39 18 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/1de7bc84-b219-43d9-a4a3-e900f68edf57">
<img width="1440" alt="Screenshot 2024-04-04 at 1 39 28 PM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/13d2964f-ae61-4b11-a464-c73ae240de59">

## Testing Steps / QA Criteria

- View logged out page
- View mobile logged out page
- Log in 
- View home page
- View mobile home page

2024-04-04 20:24 UTC, flbarfield commented
It's looking so goooood!!!!

I'm noticing some wonk with the input boxes and text on the login screen, though, at certain widths

<img width="526" alt="Ex1" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/14006060/a

<img width="497" alt="ex2" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/14006060/f8f9a631-ba78-476f-9a36-5296babd94a4">
2a0293d-0827-4ced-9ae9-677d99d90121">

2024-04-04 21:30 UTC, bdanzer commented on src/index.css
I mentioned this in our [channel](https://the-collab-lab.slack.com/archives/C06FWHTGYCV/p1712265955006869). Since we haven't done a lot of CSS in this cohort there hasn't been an opportunity to bring this up. But components and css should be isolated together. Having global css files with changes can cause all kinds of issues and generally speaking most companies are not using files like these anymore.

2024-04-05 00:20 UTC, aberger3647 requested changes
Borders on mobile screen size, homepage view

2024-04-05 05:46 UTC, jtkabenni commented
Hey @aberger3647  and @flbarfield , I made the following changes:
- created separate css files for AddListForm, LoggedOut, SelectListForm, and removed those styles from index.css
- changed the sizing of all the headers in web (you will have to adjust the headers list view according to what looks right)
- added an image for the logged out page image. @aberger3647 if you want to try to create it in css please feel free to.
- updated our app name to clevercart
- added borders where needed and removed it in some other places so they wouldn't double up

2024-04-05 20:24 UTC, aberger3647 approved these changes
Looks awesome. Thanks for updating the border and breaking out the CSS files

2024-04-05 21:02 UTC, merged