Feature/ts-rb-purchase-date-util #11
the-collab-lab/tcl-67-smart-shopping-list pull request #43
Opened 2024-03-07 16:16 UTC by flbarfield

## Description

In order to advise users about when to purchase things, the app needs to be able to calculate that guess and store it a future date.

The calculateEstimate function from the @the-collab-lab/shopping-list-utils module will help us know how many days in the future a purchase should happen. In order to use calculateEstimate, we need to know how many days have passed since the time the item was last purchased.

## Related Issue

Issue #11 

## Acceptance Criteria

- [ ]  When the user purchases an item, the item’s dateNextPurchased property is calculated using the calculateEstimate function and saved to the Firestore database
    - [ ]  dateNextPurchased is saved as a date, not a number

- [ ]  A getDaysBetweenDates function is exported from utils/dates.js and imported into api/firebase.js
    - [ ]  This function takes two JavaScript Dates and returns the number of days that have passed between them

## Type of Changes

Feature

## Updates

### Before

N/A

### After

N/A

## Testing Steps / QA Criteria

1. When a list item is clicked, a new value in dateNextPurchased should be entered into the database. This could be checked by looking at the individual item that was clicked, and seeing if the value has changed upon that click. 
    -  Until this is fully implemented, the dateNextPurchase that the item should be updating to is currently being console logged

2. The other half of this issue was an implementation of the getDaysBetweenDates function that will reside within the dates.js/utils file. When given two firebase-date formatted items, it will return the number of days that have passed.

2024-03-08 19:57 UTC, bdanzer commented on src/utils/dates.js
> +		const difference = startDate.toDate() - endDate.toDate();
I would improve the naming for increased readability. Each of these variables should be clear enough even for a non-coder to understand. What is the difference here?

2024-03-08 19:57 UTC, bdanzer commented on src/utils/dates.js
> +		const calculation = Math.floor(difference / ONE_DAY_IN_MILLISECONDS);
Same note on readability, what is calculation?

2024-03-08 19:58 UTC, bdanzer commented on src/utils/dates.js
> +		return;
I would suggest still returning something here

2024-03-08 19:59 UTC, bdanzer commented on src/components/ListItem.jsx
> +	function estimateAddedToNow() {
I would export this function from `utils/dates.js` and turn this into a pure function

2024-03-08 19:59 UTC, bdanzer commented on src/components/ListItem.jsx
> +	function estimateAddedToNow() {
Also from a readability standpoint I am having a hard time understanding what this function does.

2024-03-08 20:00 UTC, bdanzer commented on src/utils/dates.js
> +		if (calculation <= 0) {
alternative way to write:

```javascript
if (calculation <= 0) {
	return 0;
} 

return calculation;
```

2024-03-08 22:42 UTC, adidalal requested changes

2024-03-08 22:42 UTC, adidalal commented on src/components/ListItem.jsx
> +	}
💯 to moving out the date manipulation bit to utils.

2024-03-08 22:42 UTC, adidalal commented on src/utils/dates.js
> +export function getDaysBetweenDates(startDate, endDate) {
consider keeping your functions atomic and doing "business logic" in firebase.js to compose them

Here's one thought on how to split up the functions: getFutureDate / getDaysBetweenDates / isMoreThanADayOld

2024-03-08 22:42 UTC, adidalal commented on src/api/firebase.js
You would need to modify `updateItem` otherwise your calculations won't actually get persisted

2024-03-10 00:02 UTC, jtkabenni commented on src/api/firebase.js
> +	const smartNextPurchaseEstimate = calculateEstimate(
this should be `let`

2024-03-10 00:03 UTC, jtkabenni reviewed
Hey @flbarfield and @TishShaw , getting this error when trying to mark an item as purchased, think something in your firebase function is a const when it should be let. 
![Screenshot 2024-03-09 at 5 00 03 PM](https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/6f1bfd2c-4ec4-401e-933b-13b654f7b919)

2024-03-10 04:10 UTC, bdanzer commented on vite.config.js
> +		pool: 'vmThreads',
NOTE: I added this to fix our tests 😄

2024-03-10 04:13 UTC, bdanzer commented on src/api/firebase.js
> +	const today = new Date();
I created a PR to showcase this but I would try to separate logic into separate functions. It's a bit easier to show in a separate PR: 

https://github.com/the-collab-lab/tcl-67-smart-shopping-list/pull/47

2024-03-10 17:40 UTC, merged