Fix selected list to display in dropdown
the-collab-lab/tcl-67-smart-shopping-list pull request #93
Opened 2024-03-29 05:18 UTC by TishShaw

## Description

This pull request displays the selected list name in the dropdown once selected by a user.

## Related Issue
#69 

## Acceptance Criteria
Selected list name is displayed once clicked in dropdown.

## Type of Changes
Bug fix

## Updates

### Before
<img width="1038" alt="Screenshot 2024-03-23 at 5 44 31 AM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/92543814/4a9e1c3e-1d5a-465c-9e8a-5e6272833563">

### After
<img width="1141" alt="Screenshot 2024-03-23 at 5 37 25 AM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/92543814/4bc0d7a2-0243-4706-8964-950cfc25a26b">

## Testing Steps / QA Criteria

1. The user has a list of shopping lists.
2. Once the user selects a specific list in the dropdown it is shown to be selected in the dropdown and matches the list name on the top on the web page.

2024-03-29 06:19 UTC, jtkabenni requested changes
Hey Tish, right now if I select a list and then refresh, the list name dissapears from the dropdown. The same thing happens if I go to the list view, then return to the home page. 
<img width="1437" alt="Screenshot 2024-03-29 at 12 18 41 AM" src="https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/18d122db-ce95-4ea7-b513-b33ca7f41830">

2024-03-29 06:19 UTC, jtkabenni commented on src/context/UserProvider.jsx
> +	console.log(user);
Remove

2024-03-29 06:19 UTC, jtkabenni commented on src/components/SelectListForm.jsx
> -				<h3>
I think we want to keep this h3 inside the div and where it is originally. this is according to the lofi mockup layout.

2024-03-29 17:22 UTC, aberger3647 requested changes

2024-03-29 17:22 UTC, aberger3647 commented on src/components/SelectListForm.jsx
We aren't using listPath that was sent in as props from Home. What if we sent in listName instead and used listName as the initial value of the useState for setSelectedList?

2024-03-29 17:30 UTC, jtkabenni commented on src/components/SelectListForm.jsx
Yes that's a good idea!! @aberger3647

2024-03-30 17:53 UTC, jtkabenni requested changes
Hey Tish, still not seeing the expected behavior. I would make sure whatever is needed to display the listName in the select dropdown is actually getting passed to the correct component. 
![Screenshot 2024-03-30 at 11 44 16 AM](https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/ce9fa499-b160-4aca-81b8-aa727428b44f)



Also, when there is no list selected, it is showing a blank dropdown when it should display something like "Select a list", as Alex mentioned in her comment. You can take a look at her comment to see a suggested way of implementing this. 

![Screenshot 2024-03-30 at 11 48 20 AM](https://github.com/the-collab-lab/tcl-67-smart-shopping-list/assets/46732901/e7e2fcf8-d998-442b-a6ca-e7778a04c69a)


I would also recommend running through the user flow locally to make sure the expected behavior exists before re-requesting reviews. Thanks!

2024-03-30 17:53 UTC, jtkabenni commented on src/components/SelectListForm.jsx
> +	listName,
You need to make sure this prop is actually being passed in. Where is it being passed in from?

2024-03-30 17:53 UTC, jtkabenni commented on src/components/SelectListForm.jsx
> +	const [selectedList, setSelectedList] = useState(listName);
You can set a default state here for if no list is selected, something like "No list Selected"

2024-04-01 04:05 UTC, aberger3647 commented
Currently, if I select a list and then go to that list, then return to the home page, it still shows "Select a list". See my reply to Jenny for a suggestion on fixing that behavior

2024-04-04 17:10 UTC, aberger3647 approved these changes
Great solution!

2024-04-04 17:10 UTC, aberger3647 commented on src/components/SelectListForm.jsx
> +	const [selectedList, setSelectedList] = useState(listName);
@jtkabenni I tried this and it worked while on the Home page, but when I viewed the list and returned to the home page, it went back to that default state. The only way I have been able to make this work the way we expect is to set the default to listName, and add a condition in the component body:
`	if (!listName) {
		setSelectedList('No list selected')
	}`

2024-04-04 17:30 UTC, jtkabenni approved these changes

2024-04-04 17:30 UTC, merged